HR/HRPortal/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from django.views.generic import RedirectView

urlpatterns = [
    re_path(r'^admin/$', RedirectView.as_view(url='/admin/employees'), name='admin'),
    path('admin/employees/', include('employee.urls'), name='employees'),
    path('superadmin/', admin.site.urls, name='superadmin'),
    path('logout/', auth_views.LogoutView.as_view(), name='auth_logout')
]

HR/employee/urls.py
from django.urls import path
from .views import dashboard, create_employee, view_employee, check_email_availability

app_name = 'employee'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('create', create_employee, name='create_employee'),
    path('<uuid:uuid>', view_employee, name='view_employee'),
    path('check_email_availability', check_email_availability, name='check_email_availability'),
]

HR/employee/models.py
import uuid
from random import random

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

from django_countries.fields import CountryField
from django_fsm import FSMField
from phonenumber_field.modelfields import PhoneNumberField

from core.enums import MaritalStatus, SupervisorType, Gender, UserStates, EmployeeType, Company, \
    ProbationPeriod, NetOrGross
from core.models import Model


# Create your models here.
class Employee(Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, null=False, editable=False)
    user_type = models.CharField(max_length=3, choices=EmployeeType.choices, default=EmployeeType.INTERNAL, blank=False)
    uuid = models.UUIDField(editable=False, default=uuid.uuid4)
    date_of_birth = models.DateField(blank=False, null=False)
    gender = models.CharField(max_length=1, choices=Gender.choices, default=None, blank=True, null=True)
    nationality = CountryField(blank=False, default=None)
    disability = models.BooleanField(default=False, blank=False, null=False)
    marital_status = models.CharField(max_length=15, choices=MaritalStatus.choices, default=None, null=False)
    residential_country = CountryField(blank=False, default=None)
    residential_address = models.CharField(max_length=255, blank=False, null=False)
    residential_city = models.CharField(max_length=50, blank=False, null=False)
    residential_postal_code = models.CharField(max_length=10, blank=True, null=True)
    residential_phone = PhoneNumberField(blank=True, null=True)
    personal_email = models.EmailField(blank=False, null=False)
    employees_managed = models.ManyToManyField(
        'self',
        related_name='managers',
        symmetrical=False,
        through='Supervisor')
    state = FSMField(choices=UserStates.choices, default='draft', protected=True, null=False)

    def get_supervisors_by_type(self, type):
        return getattr(self.to_employee.filter(supervisor_type=type).first(), 'from_employee', None)

    def __str__(self):
        return f"""PW{self.user_id} : {self.user.first_name} {self.user.last_name}"""


class Supervisor(Model):
    from_employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='from_employee')
    to_employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='to_employee')
    supervisor_type = models.CharField(max_length=2, choices=SupervisorType.choices, default=None, blank=True)

    class Meta:
        unique_together = ['from_employee', 'to_employee']


class ContractCategory(Model):
    contract_category = models.CharField(max_length=10)


class ContractType(Model):
    contract_type = models.CharField(max_length=10)
    contract_category = models.ForeignKey(ContractCategory, on_delete=models.DO_NOTHING)


class LegalEntity(Model):
    legal_entity = models.CharField(max_length=10)
    country = CountryField(blank=False, null=False)


class Contract(Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='contract')
    city = models.CharField(max_length=25, blank=False, null=False)
    company = models.CharField(max_length=10, choices=Company.choices, default=Company.JUMIA, blank=False)
    contract_type = models.ForeignKey(ContractType, on_delete=models.DO_NOTHING)
    legal_entity = models.ForeignKey(LegalEntity, on_delete=models.DO_NOTHING)
    start_date = models.DateField(blank=False, null=False)
    end_date = models.DateField(blank=True, null=True)
    probation_period = models.CharField(
        max_length=10,
        choices=ProbationPeriod.choices,
        default=ProbationPeriod._NA,
        blank=False,
        null=False)


class Salary(Model):
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    annual_basic_salary = models.PositiveIntegerField(blank=False, null=False)
    currency_code = models.CharField(max_length=10, blank=False, null=False)
    effective_date = models.DateField(blank=False, null=False)


class Entitlements(Model):
    salary = models.ForeignKey(Salary, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(blank=False, null=False)
    include_in_salary = models.BooleanField(default=False, blank=False, null=False)
    net_or_gross = models.CharField(max_length=1, choices=NetOrGross.choices, blank=False, null=False)


@receiver(pre_save, sender=Employee)
def create_user(sender, instance, raw, **kwargs):
    user = User(email=instance.email,
                first_name=instance.first_name,
                last_name=instance.last_name,
                username=instance.email,
                is_active=0)
    user.save()
    instance.user_id = user.id

HR/employee/forms.py
import phonenumber_field.widgets
from django import forms
from django.contrib.auth.models import User
from django.forms import NumberInput
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from phonenumber_field.formfields import PhoneNumberField

from core.enums import EmployeeType, Gender, MaritalStatus
from .models import Employee


class EmployeeForm(forms.ModelForm):
    user_type = forms.ChoiceField(choices=EmployeeType.choices, required=True)
    date_of_birth = forms.DateField(widget=forms.widgets.TextInput(attrs={'type': 'date'}))
    gender = forms.ChoiceField(choices=Gender.choices, initial=None, required=False)
    nationality = CountryField()
    disability = forms.BooleanField(required=False, initial=False, widget=forms.widgets.CheckboxInput(
        attrs={
            'type': 'checkbox'
        }
    ))
    marital_status = forms.ChoiceField(choices=MaritalStatus.choices)
    residential_country = CountryField(blank_label="(Select Country)")
    residential_address = forms.CharField(widget=forms.widgets.TextInput(attrs={
        'class': 'input', 'type': 'text', 'placeholder': 'Residential Address'
    }))
    residential_city = forms.CharField(widget=forms.widgets.TextInput(attrs={
        'class': 'input', 'type': 'text', 'placeholder': 'Residential City'
    }))
    residential_postal_code = forms.CharField(required=False, widget=forms.widgets.TextInput(attrs={
        'class': 'input', 'type': 'text', 'placeholder': 'Postal Code'
    }))
    residential_phone = PhoneNumberField(required=False, widget=phonenumber_field.widgets.PhoneNumberPrefixWidget(
        country_choices=residential_country.countries,
        attrs={
            'class': 'input', 'type': 'tel', 'placeholder': 'Phone Number'
        }))
    personal_email = forms.EmailField(widget=forms.widgets.EmailInput(
        attrs={
            'class': 'input', 'type': 'email', 'placeholder': 'Personal Email'
        }
    ))
    direct_manager = forms.ModelChoiceField(queryset=Employee.objects.all(),
                                            label='Direct Manager')

    class Meta:
        model = Employee
        exclude = ["user", "deleted_at", "state", "active", "employees_managed"]
        widgets = {"country": CountrySelectWidget()}


class UserForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.widgets.TextInput(attrs={
        'class': 'input', 'type': 'text', 'placeholder': 'First Name'
    }))
    last_name = forms.CharField(widget=forms.widgets.TextInput(attrs={
        'class': 'input', 'type': 'text', 'placeholder': 'Last Name'
    }))
    email = forms.EmailField(widget=forms.widgets.EmailInput(
        attrs={
            'class': 'input', 'type': 'email', 'placeholder': 'Work Email'
        }
    ), disabled=True)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

HR/employee/views.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect

import core.enums
from employee.forms import EmployeeForm, UserForm
from employee.models import Employee, Supervisor


# Create your views here.
def dashboard(request):
    employees = Employee.objects.all()
    employees_count = employees.count()
    employees_active_count = employees.filter(state='active').count()
    employees_leavers_count = employees.filter(state__in=['future_leaver', 'marked_as_leaver']).count()
    employees_approval_count = employees.filter(state__in=['draft']).count()

    paginator = Paginator(employees, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'employees': page_obj,
        'employees_count': employees_count,
        'employees_active_count': employees_active_count,
        'employees_leavers_count': employees_leavers_count,
        'employees_approval_count': employees_approval_count,
    }

    return render(request, 'index.html', context)


def create_employee(request):
    employee_form = EmployeeForm(request.POST or None)
    user_form = UserForm(request.POST or None)
    if (request.method == 'POST'
            and employee_form.is_valid()
            and user_form.is_valid()):
        try:
            employee = employee_form.save(commit=False)
            employee.email = user_form.cleaned_data.get('email')
            employee.first_name = user_form.cleaned_data.get('first_name')
            employee.last_name = user_form.cleaned_data.get('last_name')
            employee.save()
            supervisor = Supervisor(
                supervisor_type=core.enums.SupervisorType.DIRECT,
                from_employee=Employee.objects.get(pk=request.POST['direct_manager']),
                to_employee=employee
            )
            supervisor.save()
        except:
            # TODO ERROR
            pass
        return redirect('employee:dashboard')

    context = {
        'employee_form': employee_form,
        'user_form': user_form
    }

    return render(request, 'create_employee.html', context)


def view_employee(request, uuid):
    employee = Employee.objects.get(uuid=uuid)
    form = EmployeeForm(instance=employee, initial={'direct_manager': employee.get_supervisors_by_type('D')} or None)

    context = {
        'employee': employee,
        'form': form
    }
    return render(request, 'view_employee.html', context)


def check_email_availability(request):
    first_name = request.GET['first_name']
    last_name = request.GET['last_name']

    email = first_name + '.' + last_name + '@company.com'

    email_is_not_available = User.objects.filter(email=email).first()

    if email_is_not_available:
        response_data = {'email': None}
    else:
        response_data = {'email': email}

    return JsonResponse(response_data)

HR/employee/templates/create_employee.html
{% extends 'base.html' %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<div class="column">
    <div class="box">
        <h1 class="title is-5 has-text-grey-dark">EMPLOYEE INFORMATION</h1>
    </div>

    <div class="box">
        <div class="block">

            <!--
            {% load crispy_forms_tags %}

            {% crispy user_form %}

            {% crispy employee_form %}
-->


            <div class="section is-medium pt-2 pb-2">
                <form method="post" id="employee-create-form">
                    {% csrf_token %}

                    <div class="field">
                        <div class="control">
                            <label class="label">{{ employee_form.user_type.label_tag|title }}</label>
                            <div class="select">
                                {{ employee_form.user_type }}
                            </div>
                        </div>
                    </div>


                    <div class="field is-grouped">
                        <div class="control is-expanded">
                            <label class="label">Name:</label>
                            {{ user_form.first_name }}
                        </div>

                        <div class="control is-expanded">
                            <label class="label">&nbsp;</label>
                            {{ user_form.last_name }}
                        </div>


                        <div class="control is-expanded">
                            <label class="label">&nbsp;</label>
                            {{ user_form.email }}
                        </div>


                    </div>


                    <div class="field is-grouped">
                        <div class="control">
                            <label class="label">{{ employee_form.date_of_birth.label_tag|title }}</label>
                            <div class="date">
                                {{ employee_form.date_of_birth }}
                            </div>
                        </div>

                        <div class="control">
                            <label class="label">{{ employee_form.gender.label_tag }}</label>
                            <div class="select">
                                {{ employee_form.gender }}
                            </div>
                        </div>

                        <div class="control">
                            <label class="label">{{ employee_form.nationality.label_tag }}</label>
                            <div class="select">
                                {{ employee_form.nationality }}
                            </div>
                        </div>
                    </div>


                    <div class="field">
                        <label class="label">{{ employee_form.marital_status.label_tag|title }}</label>
                        <div class="control">
                            <div class="select">
                                {{ employee_form.marital_status }}
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <label class="label">Contact Information:</label>
                            {{ employee_form.residential_address }}
                        </div>
                    </div>

                    <div class="field is-grouped">
                        <div class="control">
                            {{ employee_form.residential_postal_code }}
                        </div>

                        <div class="control is-expanded">
                            {{ employee_form.residential_city }}
                        </div>

                        <div class="control">
                            <div class="select">
                                {{ employee_form.residential_country }}
                            </div>
                        </div>
                    </div>


                    <div class="columns is-variable is-2">


                        {{ employee_form.residential_phone }}

                        <div class="column">
                            <div class="control is-expanded">
                                {{ employee_form.personal_email }}
                            </div>
                        </div>


                    </div>


                    <div class="field">
                        <label class="label">{{ employee_form.direct_manager.label_tag|title }}</label>
                        <div class="control">
                            <div class="select">
                                {{ employee_form.direct_manager }}
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <label class="checkbox">
                            {{ employee_form.disability }} Mark if employee has disability
                        </label>
                    </div>

                    <div class="field is-grouped-right">
                        <div class="control">
                            <button class="button is-link">Submit</button>
                        </div>
                    </div>

                </form>
            </div>

        </div>
    </div>
</div>


<script>

    window.addEventListener('load', function() {
      // Wrap id_residential_phone_0
      wrapSelectWithSelect('id_residential_phone_0');

      // Wrap id_residential_phone_1
      wrapSelectWithControl('id_residential_phone_1');
    });

    function wrapSelectWithSelect(elementId) {
      var selectElement = document.getElementById(elementId);
      selectElement.value=-1;
      selectElement.placeholder="Hi";

      if (selectElement) {
        // Create a new control div element
        var columnDiv = document.createElement('div');
        columnDiv.className = 'column is-one-fifth';

        var fieldDiv = document.createElement('div');
        fieldDiv.className = 'field';

        var controlDiv = document.createElement('div');
        controlDiv.className = 'control is-expanded';

        // Create a new select div element
        var selectDiv = document.createElement('div');
        selectDiv.className = 'select';

        // Clone the select element and append it to the select div
        var clonedSelect = selectElement.cloneNode(true);
        selectDiv.appendChild(clonedSelect);

        // Append the select div to the control div
        controlDiv.appendChild(selectDiv);
        fieldDiv.appendChild(controlDiv);
        columnDiv.appendChild(fieldDiv);

        // Replace the original select element with the control div
        selectElement.parentNode.replaceChild(columnDiv, selectElement);
      }
    }

    function wrapSelectWithControl(elementId) {
      var selectElement = document.getElementById(elementId);
      if (selectElement) {

        var columnDiv = document.createElement('div');
        columnDiv.className = 'column';

        // Create a new control div element
        var controlDiv = document.createElement('div');
        controlDiv.className = 'control is-expanded';

        // Replace the original select element with the control div
        selectElement.parentNode.replaceChild(columnDiv, selectElement);

        // Append the select element to the control div
        controlDiv.appendChild(selectElement);
        columnDiv.appendChild(controlDiv);
      }
    }

</script>


<script>
    $(document).ready(function() {
      var form = $('#employee-create-form');
      var firstNameInput = form.find('#id_first_name');
      var lastNameInput = form.find('#id_last_name');
      var generatedEmail = form.find('#id_email');

      function updateGeneratedEmail() {
        var firstName = firstNameInput.val();
        var lastName = lastNameInput.val();

        if (firstName && lastName) {
          var email = firstName.toLowerCase() + '.' + lastName.toLowerCase() + '@company.com';

          // Check email availability
          $.ajax({
            url: '/admin/employees/check_email_availability',
            method: 'GET',
            data: { first_name: firstName, last_name: lastName },
            success: function(data) {
                console.log(data.email);
                generatedEmail.val(data.email);
            }
          });
        } else {
          generatedEmail.val('');
        }
      }

      firstNameInput.on('input', updateGeneratedEmail);
      lastNameInput.on('input', updateGeneratedEmail);
    });
</script>


{% endblock content %}

HR/employee/templates/employee_contracts.html
<div class="box block">
    <h1 class="title is-5 has-text-grey-dark">CONTRACTUAL INFORMATION</h1>
</div>

HR/employee/templates/employee_menu.html
<aside class="menu">
    <p class="menu-label">
        General
    </p>
    <ul class="menu-list">
        <li><a href="{% url 'employee:dashboard' %}">Dashboard</a></li>
    </ul>
    <p class="menu-label">
        Administration
    </p>
    <ul class="menu-list">
        <li>
            <a class="{% if request.resolver_match.view_name == 'employee:view_employee' %}is-active{% endif %}"
               href="{{ employee.uuid }}">Manage Employee</a>
            <ul>
                <li><a>Contracts</a></li>
                <li><a>Leaves</a></li>
                <li><a>Team</a></li>
            </ul>
        </li>
        <li><a href="#">KPIs</a></li>
        <li><a href="#">Appraisal</a></li>
    </ul>
    <p class="menu-label">
        Transactions
    </p>
    <ul class="menu-list">
        <li><a>Payments</a></li>
    </ul>
</aside>

HR/employee/templates/index.html
{% extends 'base.html' %}

{% load employees %}

{% block content %}

<div class="column">
    <div class="box">
        <nav class="level">
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Number of Employees</p>
                    <p class="title">{{ employees_count }}</p>
                </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Active</p>
                    <p class="title">{{ employees_active_count }}</p>
                </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Marked as Leaver</p>
                    <p class="title">{{ employees_leavers_count }}</p>
                </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Pending Approvals</p>
                    <p class="title">{{ employees_approval_count }}</p>
                </div>
            </div>
        </nav>
    </div>

    <div class="box">

        <nav class="level">
            <!-- Left side -->
            <div class="level-left">
                <div class="level-item">
                    <div class="field has-addons">
                        <p class="control">
                            <input class="input" type="text" placeholder="Find an employee">
                        </p>
                        <p class="control">
                            <button class="button">
                                Search
                            </button>
                        </p>
                    </div>
                </div>
            </div>

            <!-- Right side -->
            <div class="level-right">
                <p class="level-item"><strong>All</strong></p>
                <p class="level-item"><a>Active</a></p>
                <p class="level-item"><a>Drafts</a></p>
                <p class="level-item"><a>Marked Leaver</a></p>
                <p class="level-item"><a class="button is-success" href="{% url 'employee:create_employee' %}">New</a>
                </p>
            </div>
        </nav>

    </div>
    <div class="box">
        <table class="table is-fullwidth is-striped has-text-centered">
            <thead>
            <tr>
                <th class="has-text-centered">Employee Number</th>
                <th class="has-text-centered">Name</th>
                <th class="has-text-centered">Email</th>
                <th class="has-text-centered">Country</th>
                <th class="has-text-centered">Status</th>
                <th class="has-text-centered">State</th>
                <th class="has-text-centered">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for employee in employees %}
            <tr>
                <td>PW{{ employee.user_id }}</td>
                <td>{{ employee.user.first_name }} {{ employee.user.last_name }}</td>
                <td>{{ employee.user.email }}</td>
                <td>{{ employee.residential_country.name }}</td>
                <td>{% if employee.user.is_active %}Active{% else %}Inactive{% endif %}</td>
                <td>{{ employee.state }}</td>
                <td>
                    <a href="{{ employee.uuid }}">
                    <span class="icon"><i class="far fa-eye"></i>
                    </span>
                    </a>
                </td>

            </tr>
            {% endfor %}
            </tbody>
        </table>

        <nav class="pagination is-centered" role="navigation" aria-label="pagination">

            <a class="pagination-previous
            {% if employees.has_previous %}" href="?page={{ employees.previous_page_number }}">
                Previous
               {% else %}
               is-disabled">Previous
            {% endif %}</a>

            <a class="pagination-next
            {% if employees.has_next %}" href="?page={{ employees.next_page_number }}">
                Next
               {% else %}
               is-disabled">Next
            {% endif %}</a>

            <ul class="pagination-list">
                {% if employees.has_previous %}
                <li><a class="pagination-link" aria-label="Goto page 1"  href="?page=1">1</a></li>
                {% if employees.number > 2 %}
                <li><span class="pagination-ellipsis">&hellip;</span></li>
                <li><a class="pagination-link" aria-label="Goto page {{ employees.number|add:-1 }}"
                href = "?page={{ employees.number|add:-1 }}">
                    {{ employees.number|add:-1 }}
                </a></li>
                {% endif %}
                {% endif %}
                <li><a class="pagination-link is-current" aria-current="page" href="#">{{ employees.number }}</a></li>
                {% if employees.number|add:1 < employees.paginator.num_pages  %}
                <li><a class="pagination-link" href="?page={{ employees.number|add:1 }}">{{ employees.number|add:1 }}</a></li>
                <li><span class="pagination-ellipsis">&hellip;</span></li>
                {% endif  %}
                {% if employees.number < employees.paginator.num_pages  %}
                <li><a class="pagination-link" aria-label="Goto page {{ employees.paginator.num_pages }}"
                       href="?page={{ employees.paginator.num_pages }}">{{ employees.paginator.num_pages }}</a></li>
                {% endif  %}

            </ul>
        </nav>

    </div>
</div>

{% endblock content %}

HR/employee/templates/view_employee.html
{% extends 'base.html' %}

{% block content %}

<div class="column">
    <div class="box">
        <h1 class="title is-5 has-text-grey-dark">EMPLOYEE INFORMATION</h1>
    </div>
    <div class="columns">
        <div class="column is-one-fifth">

            {% include 'employee_menu.html' %}

        </div>
        <div class="column">
            <div class="card block">
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                {% if employee.gender == 'F' %}
                                <img class="is-rounded" src="https://havardassoc.co.uk/wp-content/uploads/2021/12/business-female-avatar-500x620.png" alt="Placeholder image">
                                {% else %}
                                <img class="is-rounded" src="https://connectkaro.org/wp-content/uploads/2019/03/placeholder-profile-male-500x500.png" alt="Placeholder image">
                                {% endif %}
                            </figure>
                        </div>
                        <div class="media-content">
                            <p class="title is-4">{{ employee.user.first_name }} {{ employee.user.last_name }}</p>
                            <p class="subtitle is-6">PW{{ employee.user.id }} | {{ employee.user.email }}
                                {% if employee.disability %}
                                <span class="icon"><i class="fas fa-wheelchair-move"></i></span>
                                {% endif %}
                            </p>
                        </div>
                        <div class="media-right">
                            <a href="#">
                                <span class="icon is-large"><i class="far fa-pen-to-square fa-lg"></i></span>
                            </a>
                        </div>
                    </div>

                    <div class="content">
                        <p><span class="icon"><i class="fas fa-baby"></i></span>
                            {{ employee.date_of_birth|date:'d M Y' }}
                        </p>
                        <p>
                            <span class="icon"><i class="{{ employee.nationality.flag_css }}"></i></span>
                            {{ employee.nationality.name }}
                        </p>
                        <p>
                            <span class="icon"><i class="fas fa-map-pin"></i></span>
                            {{ employee.residential_address }}
                            <br><span class="icon"></span>
                            {{ employee.residential_postal_code }} {{ employee.residential_city }}
                            <br><span class="icon"></span>
                            {{ employee.residential_country.name }}
                        </p>
                        {% if employee.residential_phone %}
                        <p>
                            <span class="icon"><i class="fas fa-mobile-screen"></i></span>
                            {{ employee.residential_phone }}
                        </p>
                        {% endif %}

                        {% if employee.personal_email %}
                        <p>
                            <span class="icon"><i class="far fa-envelope"></i></span>
                            {{ employee.personal_email }}
                        </p>
                        {% endif %}

                        <p>
                            <span class="icon"><i class="far fa-heart"></i></span>
                            {{ employee.marital_status|title }}
                        </p>


                    </div>
                </div>
            </div>
            {% if user.contract.count > 0 %}
                {% include 'employee_contracts.html' %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}